### ISSUE TITLE
vscode 1.55.2 打开开发工具提示 Application Creator 安装失败，是否重新安装。

### ISSUE THREAD

**Issue by neoyi** [appworks-lab/pack#3]
vscode 1.55.2 打开开发工具提示 Application Creator 安装失败，是否重新安装。
![image](https://user-images.githubusercontent.com/4921506/116666332-6acad680-a9cd-11eb-9476-d7c051dc05bd.png)

**Comment by luhc228** [comment]
和网络有关系？
