### ISSUE TITLE
JSON 可视化编辑能力升级

### ISSUE THREAD

**Issue by alvinhui** [appworks-lab/pack#465]
### 问题描述

目前 JSON 可视化编辑能够支持所有的 JSON 文件，但由于缺乏 schema 的支持，在非内置 Schema 的场景下体验不好。

### 建议的解决方案

社区内有 [JSON Schema Store](http://www.schemastore.org/json/) 这样的库，与这样的库结合起来，能够使得 Iceworks Config Helper 有更好的普适性和扩展性。

**Comment by imsobear** [comment]
可以考虑把单个场景做透，比如做一个很牛逼的 package.json 可视化编辑器

**Comment by alvinhui** [comment]
> 可以考虑把单个场景做透，比如做一个很牛逼的 package.json 可视化编辑器

这也是一种思路，但我觉得用复杂的可视化编辑器更新 package.json 的体验很难做好。

连接 JSON Schema Store 的话，可以让开发者只安装一个插件就都具备了 JSON 编辑辅助和可视化编辑的功能。

**Comment by alvinhui** [comment]
## 建议的技术方案

- 启动插件的时候，请求一下 API http://www.schemastore.org/api/json/catalog.json ，然后将结果缓存到本地。这样有了所有支持的 JSON Schema 列表（之后都从本地去获取这个列表）；
- 当用户打开 JSON 文件（或点击「可视化编辑 JSON」）时，从 JSON 列表里找有没有对应的 Schema（fileMatch），有的话请求缓存到本地（之后都从本地去获取这个 Schema）。

**Comment by alvinhui** [comment]
Config Helper 插件经过讨论将会在 1.0 版本下线。
