### ISSUE TITLE
收集一些常见的插件形成推荐列表

### ISSUE THREAD

**Issue by alvinhui** [appworks-lab/pack#821]
目前我们的研发套件是以自研的插件为集合的。

实际上对于一个新的前端开发者来说，安装 VS Code 后还需要安装不少社区的插件来达到更好的开发体验。

结合我们淘系的前端背景，收集一些大家常用的 VS Code 插件，形成一个 FED Pack，让新人快速集成。 

关系上的话，FED Pack 将包含 Iceworks Pack。

**Comment by imsobear** [comment]
- EditorConfig
- Eslint
- json
- npm
- Prettier
- stylelint

**Comment by sspku-yqLiu** [comment]
- Chinese (Simplified) Language Pack for Visual Studio Code
- ES7 React/Redux/GraphQL/React-Native snippets

**Comment by fyangstudio** [comment]
Code Spell Checker
GitLens — Git supercharged
Path Autocomplete

**Comment by luhc228** [comment]
- Auto close Tag: Automatically add HTML/XML close tag, same as Visual Studio IDE or Sublime Text
- Auto Rename Tag: Auto rename paired HTML/XML tag
- Bookmarks: Mark lines and jump to them. 读源码利器
- Code Runner
- Git History
- **Debugger for chrome**
- Live Server
- Path Intellisense
- TODO Highlight
- Typescript React code snippets

**Comment by luhc228** [comment]
汇总上面的 comment，FED Pack 最好不要超过 10 个插件

- FED Pack
  - Iceworks Pack
  - ESlint
  - Prettier
  - stylelint
  - Debugger for chrome
  - Path Autocomplete
  - Auto close Tag
  - Auto Rename Tag

**Comment by alvinhui** [comment]
### 排除

- EditorConfig: 不推荐安装，EditorConfig 是为了在多个编辑器上实现配置的同步，我们现在只推荐 VS Code
- ES7 React/Redux/GraphQL/React-Native snippets: 这个我感觉太多了，例如 redux/graphQL/rn 都是我们不需要的
- Path Autocomplete: 普通的 path 补全 VS Code 内置的语言服务已经提供较好的支持的，它拓展支持了更多的路径写法，但这些写法不是当前 CJS / ESM 所支持的
- Code Runner: 使用频率不高
- TODO Highlight: 比较小众，实现又比较重（多了一个 sidebar）
- json: 比较小众，实现又比较重（多了一个 sidebar）
