### ISSUE TITLE
为什么不能禁用Appworks

### ISSUE THREAD

**Issue by holidaypenguin** [appworks-lab/pack#848]
插件名/Extension: vscode 插件 AppWorks

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: win10
* Node version: 14.16.0
* npm version: 6.14.11

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

ice-works自动更新成appworks之后不能使用使用禁用功能，点击禁用会提示“无法更改 Chinese (Simplified) Language Pack for Visual Studio Code 扩展的启用，因为它提供语言包。”，为什么禁用appworks要和语言包有关系

## 您期待的正确结果/The right result you're looking forward to

可以正确禁用，并且不影响语言包

**Comment by holidaypenguin** [comment]
![image](https://user-images.githubusercontent.com/16284750/120183387-35bad980-c242-11eb-9f27-002a43878dc0.png)

**Comment by fyangstudio** [comment]
重启下 VS Code 试试呢？

**Comment by fyangstudio** [comment]
截图的错误是套件中 [中文语言](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans) 插件的提示，这个插件不能被 disabled 掉。

![image](https://user-images.githubusercontent.com/9896768/120189564-16c04580-c24a-11eb-9a88-f5a43ab2378f.png)

操作不统一的 插件 是不应该被 套件 引入，感谢您的反馈。  对带来的问题 深感抱歉。
