### ISSUE TITLE
500未知错误

### ISSUE THREAD

**Issue by dishiertiaoxian** [appworks-lab/pack#857]
插件名/Extension: AppWorks

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: Win10
* Node version: v12.22.0
* npm version: 6.14.11

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

![image](https://user-images.githubusercontent.com/71981393/120815909-daab1e80-c582-11eb-9710-7ccb21a846c5.png)

## 您期待的正确结果/The right result you're looking forward to

显示一点东西？

**Comment by fyangstudio** [comment]
VS Code 的版本是多少

**Comment by dishiertiaoxian** [comment]
> VS Code 的版本是多少
版本1.56.2(user setup)

**Comment by dishiertiaoxian** [comment]
umi 项目打开项目仪表盘就会有上面的 500 错误，打开 ICE 项目就不会了

**Comment by fyangstudio** [comment]
这个界面会请求相关包信息。本地确认网络连接没有问题吗

**Comment by dishiertiaoxian** [comment]
> 这个界面会请求相关包信息。本地确认网络连接没有问题吗

理论上是没有问题的，不然我就回复不了消息了

**Comment by fyangstudio** [comment]
可以访问 https://www.npmjs.com/ 吗

**Comment by dishiertiaoxian** [comment]
OK可以访问
![image](https://user-images.githubusercontent.com/71981393/122322398-fd144300-cf57-11eb-84cb-b11719cd3cfe.png)

**Comment by fyangstudio** [comment]
能看下 registry 配置吗？ 在 VS Code 设置中搜索 `registry` 截图就好

**Comment by dishiertiaoxian** [comment]
这样么
![image](https://user-images.githubusercontent.com/71981393/122572171-10223280-d080-11eb-97f6-e1e68c25c72c.png)

**Comment by luhc228** [comment]
我本地也无法复现出来，可以看下 VS Code 控制台有没有报错信息？help -> Toggle Develop Tools
