### ISSUE TITLE
图标丢失

### ISSUE THREAD

**Issue by TrumanDu** [appworks-lab/pack#858]
插件名/Extension: 

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: 
* npm version: 

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them
![image](https://user-images.githubusercontent.com/16727775/120874153-d4935d00-c5d7-11eb-97b4-358418ee9024.png)

**Comment by alvinhui** [comment]
vscode 1.56.2 新版本中，图标不能出来。旧的版本是可以的。
我不确定是什么原因，貌似是这个问题：
https://github.com/electron/electron/issues/28528

**Comment by luhc228** [comment]
Ref: https://github.com/microsoft/vscode/issues/125640

最新的 VS Code Insider 没有这个问题。可以跟踪上面的 issue

**Comment by luhc228** [comment]
VSCode 1.57.0 版本 图标能正常显示

**Comment by TrumanDu** [comment]
@luhc228 @alvinhui vs code 1.57.0 彻底无法使用

![image](https://user-images.githubusercontent.com/16727775/121807771-2ac36880-cc88-11eb-8a23-aface848c483.png)
