### ISSUE TITLE
win10  Doctor没有检测

### ISSUE THREAD

**Issue by cgxgg11** [appworks-lab/pack#865]
插件名/Extension:  Doctor

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: 14.16.1
* npm version: 6.14.12

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them
-  win 10  vscode 安装后 ，项目仪表盘-> 基础信息 ：提示500 遇到了未知错误，项目检测文件数 0

- 图片地址：【https://procdn1.chatgogo.cn/gogo-staging/upload/prop/1623751577000.png】

## 您期待的正确结果/The right result you're looking forward to
- 正常扫描文件，进行代码质量检测

[](url)

**Comment by fyangstudio** [comment]
仪表盘这个错误 依赖网络请求 npm 信息，有改过 npm registry 信息吗？  能访问 https://www.npmjs.com/ 吗

**Comment by fyangstudio** [comment]
#911
