### ISSUE TITLE
选择模板创建项目流程优化

### ISSUE THREAD

**Issue by ChrisCindy** [appworks-lab/pack#872]
### 问题描述/Problem Description

创建项目选择模板阶段，下一步按钮在大屏下距离过远，使用不便。

### 建议的方案/Proposal

双击选择的模板即可进入下一步。

**Comment by fyangstudio** [comment]
![image](https://user-images.githubusercontent.com/9896768/122878916-e1030e00-d36a-11eb-8504-ff0387c8f6d2.png)

**Comment by luhc228** [comment]
AppWorks@1.2.1 版本已支持。
