### ISSUE TITLE
[Weekly] 2021-07-01

### ISSUE THREAD

**Issue by fyangstudio** [appworks-lab/pack#888]
# GitHub 智能编程 Copilot 问世

[GitHub Copilot](https://copilot.github.com/) 可从注释和代码中提取上下文，并立即建议单独的行和整个函数。

![111111111](https://user-images.githubusercontent.com/9896768/124409584-2b2cbc00-dd7b-11eb-8746-0b8818b8f488.gif)

Copilot 是在 [GPT-3](https://openai.com/blog/gpt-3-apps/) 的基础上构建的，原自 [OpenAI](https://openai.com/)。

### 使用

Copilot 目前处于 Beta Preview 阶段，并且需要排队预约，笔者还在排队等待中 😂 。

预约地址：https://github.com/features/copilot/signup

#### GPT-2 VS GPT-3

|       | 规模                                                       | 目标                                                         |
| ----- | ---------------------------------------------------------- | ------------------------------------------------------------ |
| GPT-2 | 参数高达15亿个，使用了包含800万个网页的数据集，共有40GB。  | 根据所有给定文本中前面的单词，预测下一个单词。               |
| GPT-3 | 神经网络包含1750亿个神经，为全世界参数最多的神经网络模型。 | 根据所有给定文本识别主题并可生成摘要，并产生人类可以理解的自然语言 |

基于 GPT-2 的 [TabNine](https://www.tabnine.com/) 是目前比较受欢迎的代码补全工具，拥有准确的代码片段预测体验。而 Copilot 则可拥有整段代码的预测，值得期待。

注重代码质量，写可读性高的代码还是很有必要的，未来还能方便 Copilot 预测代码提升效率~

# Chrome DevTools 支持视觉仿真调试

Chrome 的 DevTools 添加了一项新功能，该功能可用于一些非常具体的可访问性测试: 模仿视力缺陷的能力，模仿色盲或视力模糊的用户如何查看您的页面。

- 在任一网页上打开 DevTools (F12)
- 点击 ESC 或在三点选项菜单中选择 show console drawer，打开控制台

- 在控制台旁边，从三点选项菜单中选择 Rendering
- 向下滚动到渲染子面板中的 “模拟视力缺陷”

![image](https://user-images.githubusercontent.com/9896768/124062093-b8fa6580-da62-11eb-9b3e-34961acd93cb.png)

可以从4种类型的视力缺陷中进行选择来模拟:

- 视力模糊
- Protanopia (难以感知红色)

- Deuteranopia (难以感知绿色)
- Tritanopia (难以感知蓝色)

- Achromatopsia (没有色觉，只能看到灰色)

![image](https://user-images.githubusercontent.com/9896768/124062152-d3ccda00-da62-11eb-8924-53eb5965fd5d.png)

快来看看我们的页面对视力缺陷群体是否友好吧~

# AppWorks 1.2.0 发布

[AppWorks](https://appworks.site/) 前端研发工具集，让前端开发更快更好更轻松。

新版本可自动推荐适合项目运行的 Codemod，完善的废弃包和文档提示，提供更好的更新体验。

![image](https://user-images.githubusercontent.com/9896768/124062163-d8918e00-da62-11eb-9580-bc4781f46290.png)

更多发布信息请见：https://github.com/appworks-lab/pack/releases

**Comment by luhc228** [comment]
## Remote Repositories
或许你有过这样一种经历：在 Github 上看到一个感兴趣的项目，想在本地的代码编辑器中看下是怎么实现的，这时你通常会把该仓库 clone 到本地，然后用 VS Code 打开项目，然后浏览代码。这个过程无疑会浪费很多时间。
​

近日，VS Code 官方发布 [Remote Repositories](https://code.visualstudio.com/blogs/2021/06/10/remote-repositories) 插件，可以在不需要执行 `git pull` 的情况下，可以直接从 VS Code 中快速浏览、搜索、编辑和提交到任何远程 GitHub 存储库。

### 在 VS Code 中查看远程仓库
Remote Repositories 插件让开发者在本地 VS Code 中查看仓库源码，并且大部分的 VS Code 插件仍然可用：

![](https://code.visualstudio.com/assets/blogs/2021/06/10/remote-repositories1.gif)

### 创建和拉取 Pull Request
开发者可以在 VS Code 中直接修改代码，并创建新分支：

![2021-07-02 13-20-32 2021-07-02 13_21_46](https://user-images.githubusercontent.com/44047106/124225113-7788b980-db39-11eb-83a5-de796998217e.gif)

配合 [Github Pull Requests and Issue](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) 插件，我们可以直接在 VS Code 中发起 PR、查看 PR 信息、对代码进行评论、合并 PR 等操作：

![image](https://user-images.githubusercontent.com/44047106/124225087-6cce2480-db39-11eb-860f-9ea6ebcfb793.png)



参考链接：

- [https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub)
- [https://code.visualstudio.com/blogs/2021/06/10/remote-repositories](https://code.visualstudio.com/blogs/2021/06/10/remote-repositories)
- [https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)
