### ISSUE TITLE
iceworks最新版是否支持vue组件库开发

### ISSUE THREAD

**Issue by rootsli** [appworks-lab/pack#890]
iceworks CLI: 3.4.4
运行iceworks init，没有看到vue模板的相关选项。如图：
![image](https://user-images.githubusercontent.com/4099803/124102554-0bec1100-da93-11eb-9b07-a938ae0a6557.png)

![image](https://user-images.githubusercontent.com/4099803/124102589-13131f00-da93-11eb-9819-3517ad565593.png)

**Comment by imsobear** [comment]
```bash
$iceworks init material @icedesign/ice-vue-material-template
```

**Comment by rootsli** [comment]
@imsobear 运行上面的命令后 只有一个block文件夹

![image](https://user-images.githubusercontent.com/4099803/124206904-e1dc3280-db16-11eb-87dd-914f02164941.png)

**Comment by imsobear** [comment]
默认都是只有 一个 block，scaffold 可以自己 `iceworks add` 添加，component 脚手架我们没做，可以自己基于 vue-cli 或者 rollup 去搞，iceworks cli 层面其实不关注每个物料的构建工具。
